### PR TITLE
fix for guild voicestates being empty

### PR DESCRIPTION
**Pull request by saanuregh**
fixes issue #311

### CODE REVIEW

**Comment by andersfylling** [comment]
What exactly does this fix? the "omitempty" value signifies that when sending the Guild object the "voice_states" should not be included if it's value is nil / empty slice.

The issue seems to be related to receiving data? How did you verify that this is a fix?

**Comment by saanuregh** [comment]
I know that, but for some weird reason, it gives the voice state.

**Comment by andersfylling** [comment]
How are you testing that? It sounds like some issue tbh

**Comment by saanuregh** [comment]
I just called the getGuild() with a command printed content of the guild.VoiceStates, without the fix it gave empty output with and without ignore cache flag

**Comment by andersfylling** [comment]
from what you've stated I'm not able to reproduce this, do you have a code snippet that shows this?

**Pull request closed without merging**
