### PR TITLE
Add IsByWebhook and NotByWebhook Message Filters.

### PR DESCRIPTION
**Pull request by rtrox**
# Description

This commit adds additional default message filters for determining if a message is sourced from a Discord Webhook. Currently, IsByBot and NotByBot exist, but these will consider webhooks "not a bot," as bot will be set to false.

This leverages webhookid on messages being set or unset to determine if the message is sent by a webhook. This method is consistent with the public API docs, which recommend exactly this:

> If the message is generated by a webhook, the author object corresponds to the webhook's id, username, and avatar. You can tell if a message is generated by a webhook by checking for the webhook_id on the message object.

Source:
https://discord.com/developers/docs/resources/channel#message-object-message-structure

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I ran `go generate`
- [x] I have performed a self-review of my own code (remember to run `go fmt ./...`)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~I have made corresponding changes to the documentation~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] ~Any dependent changes have been merged and published in downstream modules~
- [ ] ~Added benchmarks if this is a performant required component (potential bottlenecks)~

### CODE REVIEW

**Comment by andersfylling** [comment]
Nice PR!
In your tests could you add a pre-condition that the getMsg function you are using works for all message types?

This is just to ensure that if getMsg ever changes, it won't affect your code =)

```go
// hasty example
if getMsg(&disgord.MessageCreate{}) == nil || getMsg(&disgord.MessageUpdate{}) == nil {
  t.Fatal("getMsg does not support message create and update events")
}

**Comment by rtrox** [comment]
@andersfylling I wasn't a huge fan of directly testing getMsg as a precondition as that method leaks too much implementation into the test -- if we adjust the webhook filters in the future to not use this function, for example, that precondition becomes defunct and MessageUpdate becomes untested again.

So instead I just switched to parametric tests to ensure we test the full flow against both event types. If you're happy with this approach, I'll submit a follow-up PR to adjust the tests for the rest of the filter types to follow a similar approach.

**Comment by andersfylling** [comment]
Oh I actually just ment that you have a statement to verify the assumption that getMsg works for both MessageCreate and MessageUpdate at the start of your tests. Just 2-3 lines in each unit test.

And yes if you throw in a bunch of commits I squash, but two clean commits or 10 clean commits are also completely okay and then i simply merge/forward.

**Comment by andersfylling** [comment]
But this looks comprehensive enough!

**Comment by rtrox** [comment]
right sorry, what I mean is -- getMsg is an implementation detail. You generally don't want to test implementation details in your unit tests, because when those implementation details change, you either break the test even though the tested code still works, or you stop protecting the workflow that you should be testing.

As an example, some other contributor may come after me and decide that there is some simpler way to access the message object safely, and stop using that function. The test would break because the getMsg function was deleted, and that contributor would need to refactor these tests.

**Comment by andersfylling** [comment]
Ah, yes. That's a good view, I appreciate that explanation.

**Pull request merged**
