### PR TITLE
clarify self-bot support (resolves #150)

### LINKED ISSUE #150: [Docs] Clarify self-bot support
Found this article regarding self bots: https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

The summary:
> Automating normal user accounts (generally called "self-bots") outside of the OAuth2/bot API is forbidden, and can result in an account termination if found.

Could be a good idea to edit the FAQ to reflect this possibility, not required but could help give people more context.

### PR DESCRIPTION
**Pull request by nikkelma**
# Description

Clarify self-bot support regarding the possibility for account termination.

### CODE REVIEW

**Comment by andersfylling** [comment]
What do you mean? It can't result in an account termination as if you had self botting.

**Comment by nikkelma** [comment]
Wanted to see how important it was to inform others that self-botting can result in account termination, so although disgord may not support it, it's simply staying within Discord's Terms of Service and therefore shouldn't really be considered when choosing a library. If it's not important, happy to close this!

**Comment by andersfylling** [comment]
I do care about spreading the word about self bots going against ToS. But Some require this feature and accepts the consequences, so I think it's nice that DiscordGo can provide such a feature.

**Comment by nikkelma** [comment]
Definitely understandable - edited FAQ to list the important "how do I get it working" question first followed by questions related to DiscordGo, roughly in the order of how important they are.

**Pull request merged**
