### PR TITLE
Bugfix/cache voicestate

### PR DESCRIPTION
**Pull request by Jabulba**
# Description

Changes how the VoiceState cache is handled and how to get the guild voice states

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] I ran `go generate`
- [X] I have performed a self-review of my own code (remember to run `go fmt ./...`)
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [ ] Added benchmarks if this is a performant required component (potential bottlenecks)

affects #127

### CODE REVIEW

**Comment by andersfylling** [comment]
So first off. The Guild object should have the VoiceStates field, as defined in the Discord docs. This is also required in the guild create event.

Because of the mentioned above you must still handle the voice state field on guild create. Note I believe that this is only the case in guild create events, i suggest consulting the discord docs just in to be certain.

While the Guild.GetVoiceStates idea is cool, using the *Client directly will not conform with planned test suites, as that requires the Session interface. Instead I suggest updating the VoiceStates whenever the Guild object is constructed by DisGord, and add a GetVoiceStates(guildID) to the Session interface.

How do you feel about this?

https://github.com/andersfylling/disgord/issues/81

**Comment by Jabulba** [comment]
Yea, I was wondering how to initialize the VoiceState when connecting, I'll have to use the VoiceState field from the guild.

The *Client is the reason I created the pull request early, I don't think it should be needed at all, but I'm not entirely sure how to proceed with this because the Guild object requires access to the Clients cache object. The alternative I was considering is exactly the one you mentioned, move GetVoiceState to the Session. Another idea was to store a *client field for the guild when creating the object but that doesn't feel good for tests

**Comment by andersfylling** [comment]
Yeah, adding a client instance does seem to make everything easier at
first. But it becomes difficult and limiting later on

**Comment by andersfylling** [comment]
How is this going?

**Comment by andersfylling** [comment]
I assume this is discontinued? @Jabulba

**Pull request closed without merging**
