### PR TITLE
feat: threads

### PR DESCRIPTION
**Pull request by jollyroger-jelly**
# Description
Adding interfaces to allow users to deal with threads. Using [this](https://discord.com/developers/docs/topics/threads) as my reference.

## Breaking Change?
yes. new webhook query parameter

## Benchmarks
I don't think I need benchmarks for this, but please let me know if I'm wrong

# Checklist:

- [x] I have performed a self-review of my own code
- [x] Commented complex situations or referenced the discord documentation
- [x] Updated documentation
- [x] Added/Updated unit tests
- [ ] Added/Updated benchmarks (if this is a performance critical component)

### CODE REVIEW

**Comment by jollyroger-jelly** [comment]
In short, a thread is type of channel, but with a few new, nullable fields.

Should I implement convenience functions for people, such as being able to specifically get only channels that are threads, or should I leave that as something for users to do themselves?

I can argue both sides of the issue myself, but I'd definitely like to hear other opinions.

**Comment by jollyroger-jelly** [comment]
> In short, a thread is type of channel, but with a few new, nullable fields.
> 
> Should I implement convenience functions for people, such as being able to specifically get only channels that are threads, or should I leave that as something for users to do themselves?
> 
> I can argue both sides of the issue myself, but I'd definitely like to hear other opinions.

Irrelevant question due to https://discord.com/developers/docs/resources/guild#get-guild-channels

**Review by andersfylling — APPROVED** [review]
LGTM! Thank you for the contribution!

**Pull request merged**
