### PR TITLE
Add message components

### PR DESCRIPTION
**Pull request by Acnologla**
# Description

Basically "InteractionApplicationCommandCallbackData" is a message with fewer fields, so it doesn't make sense to be a separate type.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Benchmarks
If this PR requires benchmarks (say it is an very dependent component or takes a lot of resources/use, use pprof if you need to) then the benchmarks are provided before and after such that we can make logical decisions.
Note that if you add a benchmark and find your solution to run slower, the code might still be valuable so your results are welcomed anyways!
If no benchmarks are needed, feel free to delete til paragraph.

# Checklist:

- [ ] I ran `go generate`
- [ ] I have performed a self-review of my own code (remember to run `go fmt ./...`)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added benchmarks if this is a performant required component (potential bottlenecks)

### CODE REVIEW

**Comment by andersfylling** [comment]
If this is changed to Message, the message struct must be updated to avoid sending too much information via "omitempty". While another struct seems redundant, it's actually a little nice, cause lib users know exactly what arguments they can give and we don't have to care about how the Message type is displayed when used for this endpoint.

**Comment by Acnologla** [comment]
The problem is that not all accepted fields are listed in https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata. I've done some tests and you can send fields like "Components", and it works perfectly.

**Comment by andersfylling** [comment]
Does the added Components affect the product?

**Comment by Acnologla** [comment]
yes

**Comment by Acnologla** [comment]
yes

**Comment by andersfylling** [comment]
Alright, ill re-open this. I think we can add omitempty to every message
field. As the message type is kinda read only.

**Comment by Acnologla** [comment]
maybe MessageCreateParams?

**Comment by andersfylling** [comment]
I think we should make a issue or PR at https://github.com/discord/discord-api-docs/pulls

Then just stick to whatever the docs says. Discord employees have consistently shown and stated that whatever is not in the docs, should not be used as it might be removed or changed at any time. That way we at least have some stability.

**Comment by Acnologla** [comment]
> I think we should make a issue or PR at https://github.com/discord/discord-api-docs/pulls
> 
> Then just stick to whatever the docs says. Discord employees have consistently shown and stated that whatever is not in the docs, should not be used as it might be removed or changed at any time. That way we at least have some stability.

So today they added "Components" as a field to https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata. Apparently they are adding fields gradually. So what do you think? we can put "createMessageParams" for future updates or, for now, we can just add the Components field to the "interacInteractionApplicationCommandCommandbackData".

**Comment by andersfylling** [comment]
Yeah, I think reflecting the docs and gradually adding changes is nice. We keep the same data type, which means no one has to re-write code, only append fields that want on updates.

**Comment by andersfylling** [comment]
I think this is still using CreateMessageParams

**Comment by Acnologla** [comment]
> I think this is still using CreateMessageParams

oops

**Comment by andersfylling** [comment]
awesome!

**Pull request merged**
