### PR TITLE
Replace Guild.LoadAllMembers with more suitable Client.LoadMembers

### LINKED ISSUE #190: Guild.LoadAllMembers does not check for duplicates
**Describe the bug**
Right now Guild.LoadAllMembers is pretty straightforward and litterally just fetches all members of the REST API and adds those members to the Guild.Members slice. However there does not seem to be any duplicate checking, causing the Guild.Members to have duplicated member entries.

**Expected behavior**
Guild.LoadAllMembers to add non existing members to the Guild struct.

**Desktop (please complete the following information):**
 - Golang version: 1.13 windows/amd64
 - Using Go modules? yes
 - Using Disgord v0.12.0-rc4

### LINKED ISSUE #193: Member is missing internalUpdate

### PR DESCRIPTION
**Pull request by paulhobbel**
# Description

DisGord has a Guild.LoadAllMembers function, this function is supposed to fetch all members of a guild and cache them. There are currently two issues with this function. The first issue is that this function will only work for guilds up to 1000 members. Furthermore, the function does not check for duplicated members which causes an incorrect slice of members.

This PR will move the Guild.LoadAllMembers function to Client.LoadMembers. The function uses Discord's Gateway to request members using the [Request Guild Members](https://discordapp.com/developers/docs/topics/gateway#request-guild-members) command. This command will trigger multiple [Guild Member Chunk](https://discordapp.com/developers/docs/topics/gateway#guild-members-chunk) events. Each chunk can hold up to 1000 members.

The function can now also be used to fetch members from multiple guilds and fetch by query as the function supports a `*RequestGuildMembers` as second parameter.

When I started working on this PR the idea was to only fix #190. While adding a function to check if a member already existed in the members slice I found out the Member struct did not implement `internalUpdater` yet, causing the Member.userID to be 0 (#193) this has been fixed in this PR as well.

Fixes #190 
Fixes #193 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I ran `go generate`
- [x] I have performed a self-review of my own code (remember to run `go fmt ./...`)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added benchmarks if this is a performant required component (potential bottlenecks)

### CODE REVIEW

**Comment by andersfylling** [comment]
Next release will be v0.12, so in case you want this included in that release I'm open to review this asap :)

**Comment by paulhobbel** [comment]
I believe I only miss the limit check so it currently does not know when it's done. I actually discussed this feature with other people and all seem to say the same. Don't check at all, keep it as a "scheduled request" and let others deal how they wanna check if everything is loaded

**Comment by andersfylling** [comment]
It sounds like the suggestion is to not have a synchronous method then?

**Comment by paulhobbel** [comment]
Correct, but not sure if you agree

**Comment by paulhobbel** [comment]
It's more like a "start sync process in the background" kinds thing

**Comment by andersfylling** [comment]
Yeah I guess :thinking: 
How about we remove the entire method then? The PR does solve other issues which is nice.

If the LoadMembers runs in the background anyways, it might be cleaner to just do client.Emit(......)

**Comment by paulhobbel** [comment]
Aight if you agree I can remove it as it has no benefits anymore.

**Comment by andersfylling** [comment]
Yeah, whole thing is a bit weird. But that's discord for ya..

**Comment by paulhobbel** [comment]
As discussed, removed the LoadMembers function completely as it fails to load members successfully

**Pull request merged**
