### PR TITLE
Support command handling

### PR DESCRIPTION
**Pull request by Lukaesebrot**
# Description

I am working on a command handling system included in disgord with the help of @andersfylling.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] I ran `go generate`
- [ ] I have performed a self-review of my own code (remember to run `go fmt ./...`)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by andersfylling** [comment]
To support arg parsing the logic must first;
1. Clean the input (remove spaces, tabs, before thr first normal character. Special ASCII spaces can be ignored)
2. Verify the cmd prefix to match
3. Link the next word to a command.

I guess storing the commands as a map with name as a key makes that easy peacy. But since map keys must be unique, the register method must panic on command input with an existing name. Panic is fine as its the developer/user at fault

**Comment by Lukaesebrot** [comment]
> To support arg parsing the logic must first;
> 
> 1. Clean the input (remove spaces, tabs, before thr first normal character. Special ASCII spaces can be ignored)
> 2. Verify the cmd prefix to match
> 3. Link the next word to a command.
> 
> I guess storing the commands as a map with name as a key makes that easy peacy. But since map keys must be unique, the register method must panic on command input with an existing name. Panic is fine as its the developer/user at fault.
> 
> Edit: link to unit test that verifies panic on incorrect input as an example:
> 
> https://github.com/andersfylling/disgord/blob/3972ff3e56e5b6420b74082a8ac52caf198ed4f2/test/integration_client_test.go#L18

Maybe we just don't panic but we just override the command which was registered before. That also supports the changing of a command's functionality while the bot is running.

**Comment by andersfylling** [comment]
I'm a bit concerned with silenced overwrites. What if we compromise it by, dropping panic and return an error instead, and we add a field to the Cmd: OverwriteExisting bool. That must be set to true when the dev wants to actually overwrite a command?

That being said, should we support a bucket system? As in adding, RegisterGuildCmd? It would allow customizing commands for a guild.

Essentially i would assume the behaviour to then be, 
```go
var cmd *Cmd
if guildMatch, ok := guildCmds[guildID]; ok {
    cmd, ok = guildMatch[cmdIdentifier]
}
if defaultCmd, ok := cmds[cmdIdentifier]; ok && cmd == nil {
    defaultCmd.Run()
}
```
Kinda psuedo code. Checking if there is a list of commands for a specific guild fiest, and fall back to the main commands if not. So RegisterCmd adds default commands, while eg. RegisterGuildCmd is guild specific.

**Comment by andersfylling** [comment]
Cause then I do see a use case for overwriting commands. Eg a guild can reconfigure it.

**Comment by Lukaesebrot** [comment]
Yeah, that sounds nice. I will think about some efficient solution later on. Thanks :D

**Comment by nikkelma** [comment]
I've been developing a command framework based off of Cobra (https://github.com/spf13/cobra), a library used heavily by CLI programs including kubernetes and etcd. If there's still interest in a command framework for disgord, I can put my work into a branch of my fork for input and review!

**Comment by Lukaesebrot** [comment]
Yeah, feel free to do that.
Currently I don't have much time and more important, nearly no motivation to do something cool. I just sit here and do nothing. I hope this will change soon so I can work more efficient on this. Sorry :/

**Comment by andersfylling** [comment]
Last I and Lukaesebrot talked, we agreed on Kingpin to deal with parsing of commands. As it seemed fairly easy to setup. That being said tho, is there a reason why you would prefer Cobra?

**Comment by nikkelma** [comment]
First, the weakest argument(s): kingping is imported by 249 godoc'ed packages, while cobra is imported by 16,832. I'd say that the ecosystem for cobra is much larger. Also, some of the biggest go projects use cobra, including kubernetes, docker (specifically moby), hugo, and etcd. I definitely trust those big projects to vet their dependencies well and choose a good implementation.

However, the stronger argument comes from analyzing the patterns of code using each library. Kingpin's docs and the libraries I found centralized all logic for all commands and subcommands into the main.go file. Similarly, the choice of what procedure to run was made static by using switch-case statements.

Cobra, on the other hand, associates the command (or sub-command) logic with the command definition, allowing delegation to lower commands and decentralizing command logic. The implementation of this pattern also allows for dynamic command addition/removal by default and well-isolated groups or subgroups of functionality.

Finally, although Kingpin or Cobra _could_ provide bot command functionality, both of these libraries seem to make a few critical assumptions. They assume that the caller/consumer of the commands will be short-lived and only handle a single invocation of any command, and they assume that some shell or terminal will handle the parsing of a string into an array of command arguments.

All of the above assumptions are invalid within a discord bot: a bot will register commands that are intended to be invoked multiple times over the lifetime of the executable; exiting out of a command in an error state should not call `os.Exit()` for easy bail-out behavior; and of course, discord messages are simply strings where no variable expansion or globbing will occur, meaning a purpose-built parser could be useful.

The framework I have currently uses patterns from cobra (even directly referencing the repo so I don't claim I came up with the architecture) but makes some core changes that bring the framework's assumptions in line with what a discord bot expects. It also includes a lightly configurable message-to-arguments parser so bot makers don't have to reinvent that wheel.

**Comment by nikkelma** [comment]
Final note: the scope of my cobra-like framework is laser-focused - provide command (and sub-command) configuration, parsing, and help docs within the context of a long-lived discord bot. Per-guild configuration and even prefix configuration is explicitly outside of the scope of my framework, as those solutions vary wildly based on the intended functionality of any given bot.

**Comment by andersfylling** [comment]
Do you have a link to your project? Cause as you stated in your first argument, I'm at first skeptical to implement something with a small community.

Also you don't need to use the functions from the main, but instead simply the parser functions to help delegate commands/sub-commands and correctly handle flags, just like a normal terminal app. I'm a bit busy now, but I'll do a more extensive analysis of all 3 project when I have more time (cobra, kingpin, yours).

**Comment by andersfylling** [comment]
merged into new branch, please add PRs to branch feature/commands-system

https://github.com/andersfylling/disgord/pull/257

**Pull request closed without merging**
